const questions = [
    "Är mest trolig att skicka ett sms till sitt ex?",
    "Skulle överleva längst på en öde ö?",
    "Har varit med på flest konserter?",
    "Är sämst på att hålla hemligheter?",
    "Skulle vara en perfekt politiker?",
    "Är mest trolig att bli miljonär?",
    "Är den största flirtaren?",
    "Skulle vinna i en matlagningstävling?",
    "Är mest trolig att skaffa flest barn?",
    "Har mest troligt haft en jobbig dejt?",
    "Är troligast att skämma ut sig på en fest?",
    "Skulle bli en bra skådespelare?",
    "Är mest trolig att flytta till ett annat land?",
    "Skulle du rädda i en nödsituation?",
    "Är mest trolig att tappa bort sin telefon?",
    "Är troligast att se alla Harry Potter-filmer på en dag?",
    "Skulle vara värst på att hålla en diet?",
    "Skulle mest troligt bli författare?",
    "Är troligast att vinna på lotto men förlora lotten?",
    "Är mest trolig att vara vaken hela natten?",
    "Skulle du helst vilja vara strandsatt med?",
    "Skulle du lita på med ditt liv?",
    "Är troligast att hamna i fängelse för något dumt?",
    "Skulle du helst inte vilja se arg?",
    "Är mest trolig att ta över världen?",
    "Är mest trolig att bli vegetarian?",
    "Skulle klara sig bäst utan internet?",
    "Är störst filmnörd?",
    "Skulle spendera mest pengar på shopping?",
    "Är mest trolig att glömma viktiga födelsedagar?",
    "Är mest trolig att ställa upp i en talangjakt?",
    "Är störst sportnörd?",
    "Skulle du helst gå på en roadtrip med?",
    "Är mest trolig att prova extremsporter?",
    "Är troligast att skapa en viral video?",
    "Skulle vara sämst på att ljuga?",
    "Är mest trolig att sova igenom en alarm?",
    "Skulle vara bäst på att lösa en konflikt?",
    "Skulle du helst vilja byta liv med för en dag?",
    "Skulle mest troligt missa sitt eget bröllop?",
    "Är mest trolig att bli en yoga-instruktör?",
    "Skulle vara den värsta chauffören?",
    "Skulle vara den bästa partnern på en quiz?",
    "Är mest trolig att äga en konstig husdjur?",
    "Skulle bli den bästa programledaren?",
    "Skulle vara den sista att inse att de har gjort något pinsamt?",
    "Skulle du helst inte vilja möta i en mörk gränd?",
    "Är mest trolig att bli en influencer?",
    "Skulle vara sämst på att spara pengar?",
    "Skulle du helst ha som din wingman/wingwoman?",
    "Är mest trolig att starta ett eget företag?",
    "Skulle överleva längst utan sin mobil?",
    "Har sett flest länder?",
    "Är bäst på att hålla tal?",
    "Skulle du anförtro dina hemligheter?",
    "Är mest trolig att vinna i Jeopardy?",
    "Skulle du helst ta med på en tidsresa?",
    "Skulle vara en perfekt reseledare?",
    "Är mest trolig att bli lärare?",
    "Är störst tekniknörd?",
    "Är mest trolig att adoptera ett husdjur?",
    "Skulle vara den bästa författaren?",
    "Är troligast att glömma var de parkerade sin bil?",
    "Är mest trolig att bli vegan?",
    "Skulle kunna ge upp choklad för alltid?",
    "Skulle vinna en talangjakt?",
    "Är mest trolig att bli en berömd skådespelare?",
    "Är mest trolig att ta en världsomsegling?",
    "Är mest trolig att skratta under allvarliga situationer?",
    "Skulle vara den värsta politikern?",
    "Är mest trolig att starta en blogg?",
    "Skulle spendera mest pengar på ett kasino?",
    "Skulle du helst vilja se som världens ledare?",
    "Skulle göra det bäst i en ökenöverlevnadskurs?",
    "Är mest trolig att delta i en realityshow?",
    "Skulle vara sämst på att vara en spion?",
    "Skulle vara den bästa superhjälten?",
    "Är mest trolig att ha ett hemligt liv?",
    "Är mest trolig att bli förälskad i en kändis?",
    "Skulle överleva längst på en budget?",
    "Är mest trolig att skapa en app?",
    "Skulle vinna en ätartävling?",
    "Skulle du rädda först från en översvämning?",
    "Är mest trolig att gråta på en film?",
    "Skulle vara den sista att få veta de senaste skvallren?",
    "Är mest trolig att delta i en protest?",
    "Är mest trolig att gå vilse i en storstad?",
    "Skulle bli en bra personlig tränare?",
    "Skulle vara den sämsta kocken?",
    "Är mest trolig att ha en hemlig identitet?",
    "Skulle du helst ha som sidekick i en actionfilm?",
    "Är mest trolig att vinna en Nobelpris?",
    "Är mest trolig att ändra sitt yrke helt?",
    "Skulle klara sig bäst på en improviserad komediscen?",
    "Skulle vara den sämsta bilföraren?",
    "Skulle ha den mest framgångsrika YouTube-kanalen?",
    "Är mest trolig att vara vaken först på morgonen?",
    "Skulle vara den värsta revisorn?",
    "Skulle helst leva utan internet?",
    "Skulle vara den bästa värden på en fest?",
    "Är mest benägen att ha haft en one night stand?",
    "Skulle du vilja byta kropp med för en dag på grund av deras sex appeal?",
    "Är ansedd som bäst i sängen i detta rum?",
    "Har troligast haft sex utomhus?",
    "Tros ha en hemlig samling sexleksaker?",
    "Skulle du vilja se i en sexig outfit?",
    "Tros ha haft flest sexpartners?",
    "Ansedd som den vildaste i sängen?",
    "Mest trolig att ha haft en trekant?",
    "Skulle du vilja ha en erotisk dröm om?",
    "Troligast att ha skickat nakenbilder?",
    "Skulle du välja för en het kyss?",
    "Tros ha haft en 'KK'?",
    "Har den sexigaste rösten?",
    "Ansedd som mest flirtig på fester?",
    "Skulle troligen ha den mest intressanta erotiska dagboken?",
    "Skulle kunna vara undercover som strippa?",
    "Skulle kunna göra en karriär som erotisk romanförfattare?",
    "Mest trolig att ha hemliga beundrare?",
    "Har den mest oemotståndliga charm?",
    "Misstänkt för att ha en fetisch ingen vet om?",
    "Mest benägen att bli kär vid första ögonkastet?",
    "Skulle kunna hålla på en sexig hemlighet?",
    "Troligast att prova erotiska spel?",
    "Skulle kunna vara en mästare på förförelse?",
    "Skulle kunna ha en hemlig kärleksaffär?",
    "Har mest sannolikt haft ett förhållande med en kändis?",
    "Mest benägen att kyssa och berätta?",
    "Skulle kunna skriva en sexkrönika?",
    "Har sannolikt de mest spännande sexhistorierna",
    "Troligast att smyga på första dejten?",
    "Skulle kunna vara den perfekta dominatrix?",
    "Har den mest förföriska dansen?",
    "Skulle vara mest benägen att gå på blinddate?",
    "Skulle vara bäst på att hålla sitt kärleksliv hemligt?",
    "Troligast att bli upptäckt med att vara otrogen?",
    "Har mest sannolikt en hemlig kärleksrelation?",
    "Skulle vara en naturlig på en erotisk filmset?",
    "Skulle kunna leda en sexuell hälsoworkshop?",
    "Har den mest provocerande klädstilen?",
    "Skulle kunna skapa den hetaste datingprofilen?",
    "Tros njuta mest av erotisk litteratur?",
    "Skulle kunna vara framgångsrik som telefonsexoperatör?",
    "Troligast att vara öppen för en öppen relation?",
    "Skulle kunna vara mest innovativ i sovrummet?",
    "Har mest sannolikt en hemlig porr-samling?",
    "Tros vara den största romantikern?",
    "Skulle kunna hålla den längsta förspelsessionen?",
    "Skulle vara mest benägen att testa exotiska sexställningar?",
    "Har den mest dristiga fantasin?",
    "Skulle mest troligt skicka ett pinsamt sms till fel person?",
    "Är mest trolig att bli kär i sin bästa väns partner?",
    "Skulle kunna kyssa en främling på en fest?",
    "Skulle sannolikt prova på speed dating?",
    "Är mest trolig att ha en hemlig beundrare?",
    "Skulle mest troligt gå på en blinddejt arrangerad av en vän?",
    "Skulle flirta med en polis för att komma undan en biljett?",
    "Är mest trolig att bli 'ghostad' efter en dejt?",
    "Skulle säga 'jag älskar dig' först?",
    "Skulle mest troligt spela 'truth or dare' på en första dejt?",
    "Skulle mest troligt ha en krånglig kärlekstriangel?",
    "Är mest trolig att glömma namnet på personen de dejtar?",
    "Skulle ha en hemlig crush på en kollega?",
    "Skulle gå på flest Tinderdejter på en vecka?",
    "Skulle bli upprörd om de fick reda på att deras ex dejtar någon ny?",
    "Skulle mest troligt ha en online-romans?",
    "Är mest trolig att bli kär på semestern?",
    "Skulle kunna delta i ett reality-TV-program om dejting?",
    "Skulle ha mest troligt en dejt som slutar med en natt i arresten?",
    "Är mest trolig att skaffa en matchande tatuering med en partner?",
    "Skulle mest troligt prova på partnerbyte på en fest?",
    "Är mest trolig att prova på online dejting?",
    "Skulle kunna bli förälskad i någons röst utan att ha sett personen?",
    "Skulle mest troligt hålla handen på första dejten?",
    "Skulle mest troligt ta med en vän på en dejt som backup?",
    "Skulle kunna springa en maraton utan träning?",
    "Skulle kunna äta två hela pizzor själv?",
    "Är mest trolig att vinna en frågesport?",
    "Skulle troligen bli bäst på att måla om de provade?",
    "Skulle kunna ge upp choklad för ett år?",
    "Är mest trolig att skratta under en allvarlig situation?",
    "Skulle mest troligt starta sitt eget företag?",
    "Skulle mest troligt förlora sina nycklar eller mobil?",
    "Skulle kunna prata i timmar om ingenting?",
    "Skulle kunna klara sig bäst utan teknologi?",
    "Skulle kunna spendera mest pengar på kläder?",
    "Är mest trolig att råka låsa sig själv ute ur sitt hem?",
    "Skulle kunna skriva en bok?",
    "Är mest trolig att skaffa ett husdjur?",
    "Skulle kunna lära sig ett nytt språk snabbast?",
    "Är mest trolig att falla på en offentlig plats?",
    "Skulle mest troligt glömma en viktig händelse?",
    "Skulle kunna campa i vildmarken i en vecka?",
    "Skulle kunna vara vaken i 48 timmar?",
    "Är mest trolig att bli vegetarian?",
    "Skulle mest troligt prova bungyjump?",
    "Är mest trolig att köpa något impulsivt dyrt?",
    "Skulle mest troligt börja sjunga i offentliga sammanhang?",
    "Skulle kunna bli bästa vän med en kändis?",
    "Skulle kunna adoptera en hemlös katt?"
    ];

let shuffledQuestions = shuffleArray([...questions]);
let index = 0;

function shuffleArray(array) {
    for (let i = array.length - 1; i > 0; i--) {
        const j = Math.floor(Math.random() * (i + 1));
        [array[i], array[j]] = [array[j], array[i]];
    }
    return array;
}

function questionGenerator() {
    if (index >= shuffledQuestions.length) {
        shuffledQuestions = shuffleArray([...questions]);
        index = 0;
    }

    let text = shuffledQuestions[index++];

    console.log(index - 1);
    document.getElementById('pekButton').innerHTML = 'Nästa fråga';
    document.getElementById('pekQuestion').innerHTML = text;
}