const wordMap = new Map([  ['1', ['ananas', 'bok', 'cykel', 'djur', 'elektronik']],
    ['2', ['fågel', 'grönsak', 'häst', 'is', 'jordnöt']],
    ['3', ['kaffe', 'ljus', 'mus', 'näsa', 'olja']],
    ['4', ['päron', 'robot', 'sallad', 'sol', 'tåg']],
    ['5', ['uggla', 'växt', 'xylofon', 'yoghurt', 'zeppelinare']],
    ['6', ['apelsin', 'boll', 'choklad', 'dator', 'elektriker']],
    ['7', ['fisk', 'gräs', 'hund', 'isbit', 'jaguar']],
    ['8', ['kamel', 'lampa', 'myra', 'nål', 'olika']],
    ['9', ['pizza', 'quinoa', 'råtta', 'skor', 'tiger']],
    ['10', ['unge', 'vatten', 'xenon', 'ytterkläder', 'zoom']],
    ['11', ['anka', 'bambu', 'cyklop', 'dagg', 'elefant']],
    ['12', ['fågelholk', 'guld', 'hälsning', 'igång', 'jag']],
    ['13', ['kniv', 'lök', 'macka', 'natt', 'oliv']],
    ['14', ['pumpa', 'quiche', 'rådjur', 'salladskål', 'tvättbjörn']],
    ['15', ['uggla', 'vante', 'xerxes', 'yoghurtkultur', 'zucchini']],
    ['16', ['albatross', 'björn', 'chokladpudding', 'delad', 'elektricitet']],
    ['17', ['flamingo', 'golf', 'hår', 'injektion', 'jazz']],
    ['18', ['kamelia', 'läsk', 'mynta', 'nötkreatur', 'olja']],
    ['19', ['potatis', 'quark', 'räv', 'stekpanna', 'tupp']],
    ['20', ['uggla', 'valp', 'xylofon', 'yacht', 'zebra']],
    ['21', ['apelsinskal', 'banjo', 'chokladkaka', 'datorspel', 'elektrisk']],
    ['22', ['fönster', 'gräs', 'hästhov', 'isglass', 'järnspik']],
    ['23', ['kakadua', 'läppstift', 'måne', 'näbb', 'orange']],
    ['24', ['pasta', 'quinoa', 'ros', 'sko', 'turist']],
    ['25', ['universum', 'vante', 'xilofon', 'yacht', 'zink']],
    ['26', ['and', 'bänk', 'cykelhjälm', 'djungel', 'elektricitet']],
    ['27', ['ananasjuice', 'band', 'cyklop', 'datorspelare', 'element']],
    ['28', ['flod', 'gränd', 'hylla', 'isbitmaskin', 'jämmer']],
    ['29', ['kaktus', 'lava', 'mustang', 'nagellack', 'optimist']],
    ['30', ['pangolin', 'qigong', 'röntgen', 'segelbåt', 'tango']],
    ['31', ['unge', 'vin', 'xylitol', 'yoga', 'zoo']],
    ['32', ['ajournera', 'bagare', 'cykla', 'diamant', 'elefantunge']],
    ['33', ['fackla', 'giraff', 'hängmatta', 'internet', 'jordbruk']],
    ['34', ['kål', 'löv', 'maskin', 'näckros', 'olivträd']],
    ['35', ['palats', 'quinoa', 'riddare', 'syrén', 'tungviktare']],
    ['36', ['uggla', 'väst', 'xenofobi', 'ytterdörr', 'zigenare']],
    ['37', ['albatross', 'badkar', 'chokladpralin', 'dykare', 'elektromagnetism']],
    ['38', ['fåtölj', 'guld', 'häftapparat', 'ironi', 'järnväg']],
    ['39', ['kanel', 'läder', 'myrstack', 'nyckel', 'oljemålning']],
    ['40', ['planka', 'quiche', 'räksmörgås', 'saffran', 'trollkarl']],
    ['41', ['uggla', 'vattenfall', 'xylograf', 'yacht', 'zooma']],
    ['42', ['aktie', 'barn', 'cyklon', 'datorvirus', 'elektroteknik']],
    ['43', ['faktura', 'gnagare', 'högstadium', 'isberg', 'jupiter']],
    ['44', ['kampanj', 'läppglans', 'mikrofon', 'nattuggla', 'olivolja']],
    ['45', ['papaya', 'quinoa', 'ris', 'skorsten', 'tropisk']],
    ['46', ['unicorn', 'vävnad', 'xantippa', 'yoga-byxor', 'zoo']],
    ['47', ['apelsinmarmelad', 'biljard', 'chokladtryffel', 'datormus', 'elit']],
    ['48', ['fyrkant', 'grill', 'hockey', 'insekt', 'jordnötssmör']],
    ['49', ['kamel', 'lakrits', 'målning', 'nödutgång', 'ostkaka']],
    ['50', ['paket', 'quinoa', 'rättvisa', 'stjärna', 'tegel']],
    ['51', ['ankare', 'bokhylla', 'chokladkaka', 'daggmask', 'elementarpartikel']],
    ['52', ['flodhäst', 'gepard', 'hjärtinfarkt', 'inspiration', 'jordmån']],
    ['53', ['kaviar', 'lön', 'myggnät', 'nyponros', 'oljefärg']],
    ['54', ['papegoja', 'quartzyt', 'rökelse', 'skateboard', 'traktor']],
    ['55', ['uggla', 'vindruva', 'xenofob', 'yttre', 'zebra']],
    ['56', ['aggregat', 'barnvagn', 'cykelhjälm', 'datormus', 'elitism']],
    ['57', ['färskost', 'glaciär', 'hällristning', 'intervju', 'järnvägsviadukt']],
    ['58', ['kalops', 'lönn', 'mjölnare', 'nässla', 'orkesterdirigent']],
    ['59', ['plommon', 'quiltning', 'regissör', 'sjukgymnast', 'tandborste']],
    ['60', ['underställ', 'vante', 'xenon', 'ytterdörr', 'zucchini']],
    ['61', ['apekatt', 'buntband', 'cylinderhatt', 'drakflygare', 'elektronstrålar']],
    ['62', ['fjäril', 'grotta', 'hjärncell', 'isbjörn', 'jodtabletter']],
    ['63', ['karamell', 'lärare', 'mobiltelefon', 'nyfikenhet', 'olivträd']],
    ['64', ['pannkakor', 'quinoa', 'rekrytering', 'sandstrand', 'toapapper']],
    ['65', ['uggla', 'vandringsled', 'xerografi', 'yacht', 'zodiak']],
    ['66', ['alpacka', 'bärbar dator', 'cyklisk', 'djungel', 'elefantnos']],
    ['67', ['fågelholk', 'gummiband', 'hackspett', 'improvisation', 'jungfruolja']],
    ['68', ['kompott', 'läppstift', 'maskot', 'näbb', 'oljelampa']],
    ['69', ['parasoll', 'quinoa', 'reservat', 'skridskor', 'tandställning']],
    ['70', ['underhåll', 'väsklås', 'xenofili', 'yta', 'zoomobjektiv']],
    ['71', ['apa', 'bläckfisk', 'cykla', 'drömfångare', 'elpris']],
    ['72', ['flygplansvinge', 'golfboll', 'hundvalp', 'ispropp', 'jordbävning']],
    ['73', ['flitig', 'pampig', 'kantig', 'pålitlig', 'snöig']],
    ['74', ['knarrig', 'stökig', 'kraftig', 'trivsam', 'lummig']],
    ['75', ['vindsnabb', 'skarp', 'tjusig', 'hjälpsam', 'livlig']],
    ['76', ['oändlig', 'sirlig', 'praktfull', 'härlig', 'kryddig']],
    ['77', ['platt', 'gul', 'mättad', 'kravlös', 'klarblå']],
    ['78', ['nyfiken', 'hjärtlig', 'bekväm', 'rymlig', 'dunkel']],
    ['79', ['skärgård', 'gemytlig', 'krusig', 'nyckfull', 'klar']],
    ['80', ['obunden', 'ivrig', 'fredlig', 'knackig', 'mjuk']],
    ['81', ['tyst', 'praktisk', 'oförglömlig', 'lugn', 'stark']],
    ['82', ['frostig', 'fläckig', 'lysande', 'graciös', 'halvfärdig']],
    ['83', ['nyskuren', 'gynnsam', 'fridfull', 'prickig', 'regnig']],
    ['84', ['otrolig', 'uppmärksam', 'liten', 'helig', 'genomskinlig']],
    ['85', ['mättad', 'lyxig', 'skrynklig', 'bitter', 'ljusgul']],
    ['86', ['ostadig', 'mjölig', 'barmhärtig', 'supertrevlig', 'naturtrogen']],
    ['87', ['krusig', 'förvånad', 'ljummen', 'stel', 'fuktig']],
    ['88', ['syrlig', 'svår', 'lycklig', 'tuff', 'mätt']],
    ['89', ['tillgiven', 'skramlande', 'sugen', 'vänlig', 'färgstark']],
    ['90', ['utstuderad', 'varm', 'elegant', 'plikttrogen', 'luddig']],
    ['91', ['fri', 'ledig', 'skör', 'mjuk', 'oförutsägbar']],
    ['92', ['kravlös', 'fördold', 'ung', 'skön', 'försiktig']],
    ['93', ['tillförlitlig', 'grönskande', 'vitmålad', 'mörkblå', 'pampig']],
    ['94', ['rundad', 'förlamande', 'klämkäck', 'stark', 'skär']],
    ['95', ['rakryggad', 'klibbig', 'sömnig', 'sirlig', 'blygsam']],
    ['96', ['tillfällig', 'svävande', 'glimrande', 'vacker', 'hög']],
    ['97', ['pigg', 'rutig', 'orolig', 'tvärvigg', 'karg']],
    ['98', ['glad', 'smidig', 'kantig', 'skrovlig', 'avslappnad']],
    ['99', ['glänsande', 'fruktig', 'upprymd', 'oskyldig', 'tunn']],
    ['100', ['välplanerad', 'lyxig', 'fyrkantig', 'skrovlig', 'trött']]
    ]);


function getRandomCard(map) {
    let i = Math.floor(Math.random() * map.size);
    let key = Array.from(map.keys())[i];
    let values = map.get(key);
    return values;
}

document.getElementById("cardBtn").addEventListener("click", () => {
    getRandomCard(wordMap);
});


document.getElementById("restart").addEventListener("click", () => {
    window.location.reload();
});